### ISSUE TITLE
[<milestone>] <description>

### ISSUE THREAD

**Issue by gomete** [open-arch/admin#1]
### Prerequisites

- [X] I have written a descriptive issue title
- [X] I have added the milestone
- [X] I have added to a project
- [X] I have searched existing issues to ensure a similar issue has not already been created

### Context

A brief description of the issue

### Depends on

- [ ] #1

### Acceptance Criteria

- [ ] A design document is created
- [ ] The architecture document is updated
- [ ] It is tested in the labs environment

### Tasks

- [ ] Create the design document
- [ ] Update the architecture document
- [ ] Test in labs environment
